---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: alertmanager-main
  namespace: prometheus
  labels:
    expose: external
  annotations:
    kubernetes.io/ingress.class: traefik-external
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
spec:
  rules:
  - host: alert-manager.dyel.io
    http:
      paths:
      - backend:
          serviceName: alertmanager-main
          servicePort: 9093