---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: alertmanager-main
  namespace: prometheus
  labels:
    expose: internal
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  rules:
  - host: alert-manager.kudoplay.net
    http:
      paths:
      - backend:
          serviceName: alertmanager-main
          servicePort: 9093