kind: Endpoints
apiVersion: v1
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels:
    k8s-app: kube-apiserver
subsets:
  - addresses:
      - ip: 10.135.0.3
      - ip: 10.135.0.4
      - ip: 10.135.0.5
    ports:
      - port: 443
        name: https