---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: prometheus-k8s
  namespace: prometheus
  labels:
    expose: external
  annotations:
    kubernetes.io/ingress.class: traefik-external
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
spec:
  rules:
  - host: prometheus.dyel.io
    http:
      paths:
      - backend:
          serviceName: prometheus-k8s
          servicePort: 9090