kind: Endpoints
apiVersion: v1
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
subsets:
  - addresses:
      - ip: 10.135.0.3
      - ip: 10.135.0.4
      - ip: 10.135.0.5
    ports:
      - port: 10251
        name: http-metrics