---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: prometheus-k8s
  namespace: prometheus
  labels:
    expose: internal
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  rules:
  - host: prometheus.stg-kudo.net
    http:
      paths:
      - backend:
          serviceName: prometheus-k8s
          servicePort: 9090