apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: prometheus
  labels:
    app: thanos-query
    thanos-peer: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-query
        thanos-peer: "true"
    spec:
      nodeSelector:
        kops.k8s.io/instancegroup: prometheus-nodes
      tolerations:
      - key: dedicated
        operator: Equal
        value: prometheusNodes
        effect: NoSchedule
      containers:
      - name: thanos-query
        image: improbable/thanos:v0.1.0
        args:
        - query
        - --log.level=debug
        - --query.replica-label=prometheus_replica
        - --cluster.peers=thanos-peers.default.svc:10900
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900