apiVersion: v1
kind: Service
metadata:
  name: thanos-peers
  namespace: prometheus
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: cluster
    port: 10900
    targetPort: cluster
  selector:
    thanos-peer: "true"